In [2]:
import torch
torch.__version__

'1.11.0'

In [3]:
# We can check the compute capbility score of our GPU using torch.cuda.get_device_capability().
torch.cuda.get_device_capability()
# https://developer.nvidia.com/cuda-gpus

(5, 0)

In [4]:
# https://pytorch.org/docs/stable/tensors.html

In [5]:
# A scalar is a single number and in tensor-speak it's a zero dimension tensor.

# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
# We can check the dimensions of a tensor using the ndim attribute.
scalar.ndim

0

In [7]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [8]:
# A vector is a single dimension tensor but can contain many numbers.

# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
# Check the number of dimensions of vector
vector.ndim
# You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([) and you only need to count one side.

1

In [10]:
# Another important concept for tensors is their shape attribute. The shape tells you how the elements inside them are arranged.

# Check shape of vector
vector.shape

torch.Size([2])

In [11]:
# Matrices are as flexible as vectors, except they've got an extra dimension.

# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX
# We get the output torch.Size([2, 2]) because MATRIX is two elements deep and two elements wide.

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
# Check number of dimensions
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# tensors can represent almost anything.

# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [16]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
# A machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In [18]:
# Let's see how to create a tensor of random numbers.
# Using torch.rand() and passing in the size parameter.

# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.8856, 0.0412, 0.2367, 0.3295],
         [0.3656, 0.9939, 0.3049, 0.3355],
         [0.3283, 0.2519, 0.2305, 0.2071]]),
 torch.float32)

In [19]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor, random_image_size_tensor.shape, random_image_size_tensor.ndim

(tensor([[[0.4136, 0.3867, 0.9586],
          [0.3680, 0.1920, 0.1744],
          [0.4714, 0.2717, 0.7791],
          ...,
          [0.9735, 0.0770, 0.7804],
          [0.3573, 0.1315, 0.5241],
          [0.8606, 0.8887, 0.7885]],
 
         [[0.7459, 0.1427, 0.9378],
          [0.1440, 0.1088, 0.3262],
          [0.0397, 0.6148, 0.9202],
          ...,
          [0.9505, 0.9143, 0.0945],
          [0.5878, 0.9854, 0.1198],
          [0.1816, 0.1214, 0.1264]],
 
         [[0.3776, 0.4455, 0.2964],
          [0.5442, 0.2011, 0.1838],
          [0.4995, 0.4418, 0.7840],
          ...,
          [0.0194, 0.9480, 0.8752],
          [0.9333, 0.4727, 0.8376],
          [0.0315, 0.9631, 0.0290]],
 
         ...,
 
         [[0.1324, 0.1832, 0.5926],
          [0.2429, 0.1531, 0.8828],
          [0.0901, 0.4712, 0.2562],
          ...,
          [0.8320, 0.3122, 0.3058],
          [0.7788, 0.2514, 0.1271],
          [0.6871, 0.9499, 0.6868]],
 
         [[0.4339, 0.5144, 0.3742],
          [0

In [20]:
# Sometimes you'll just want to fill tensors with zeros or ones.
# This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know  not to learn them).
# Let's create a tensor full of zeros with torch.zeros().

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [22]:
# We can do the same to create a tensor of all ones except using torch.ones() instead.

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [24]:
# You can use torch.arange(start, end, step) to get a range of numbers, such as 1 to 10 or 0 to 100.
# Where:
#     start = start of range (e.g. 0)
#     end = end of range (e.g. 10)
#     step = how many steps in between each value (e.g. 1)

In [25]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Sometimes you might want one tensor of a certain type with the same shape as another tensor.
# To do so you can use torch.zeros_like(input) or torch.ones_like(input) which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [27]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
# Generally if you see torch.cuda anywhere, the tensor is being used for GPU

In [29]:
# Let's see how to create some tensors with specific datatypes. We can do so using the dtype parameter.

In [30]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.ndim, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), 1, torch.float32, device(type='cpu'))

In [31]:
# Three most common issues you'll come across in PyTorch are:
#     shape issues (tensor shapes don't match up)
#     datatype issues
#     device issues

In [32]:
# Create a tensor with dtype=torch.float16.
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.shape,  float_16_tensor.ndim, float_16_tensor.dtype, float_16_tensor.device

(torch.Size([3]), 1, torch.float16, device(type='cpu'))

In [33]:
# We've seen these before but three of the most common attributes you'll want to find out about tensors are:
#     shape - what shape is the tensor? (some operations require specific shape rules)
#     dtype - what datatype are the elements within the tensor stored in?
#     device - what device is the tensor stored on? (usually GPU or CPU)

In [34]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Dim of tensor: {some_tensor.ndim}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.5565, 0.5640, 0.7953, 0.9166],
        [0.4859, 0.1437, 0.4277, 0.7280],
        [0.7959, 0.2544, 0.8583, 0.7160]])
Shape of tensor: torch.Size([3, 4])
Dim of tensor: 2
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [35]:
# When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, try to figure out what shape are your tensors? what datatype are they and where are they stored?

In [36]:
# In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

# tensor operations:
#     Addition
#     Substraction
#     Multiplication (element-wise)
#     Division
#     Matrix multiplication

In [37]:
# Create a tensor of values
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [38]:
# Add a number to it
tensor + 10

tensor([11, 12, 13])

In [39]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [40]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [41]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [42]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [43]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [44]:
# Original tensor is still unchanged 
tensor

tensor([1, 2, 3])

In [45]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor, "equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) equals: tensor([1, 4, 9])


In [46]:
# One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

In [47]:
# PyTorch implements matrix multiplication functionality in the torch.matmul() method.
# The main two rules for matrix multiplication to remember are:
#     The inner dimensions must match:
#         (3, 2) @ (3, 2) won't work
#         (2, 3) @ (3, 2) will work
#         (3, 2) @ (2, 3) will work
#     The resulting matrix has the shape of the outer dimensions:
#         (2, 3) @ (3, 2) -> (2, 2)
#         (3, 2) @ (2, 3) -> (3, 3)
#     "@" in Python is the symbol for matrix multiplication.

In [48]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [49]:
# Element-wise multiplication   [1*1, 2*2, 3*3] = [1, 4, 9]	    tensor * tensor
# Matrix multiplication         [1*1 + 2*2 + 3*3] = [14]	    tensor.matmul(tensor)

In [50]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [51]:
# Matrix multiplication (dot product)
torch.matmul(tensor, tensor)

tensor(14)

In [52]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [53]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 16.9 ms


tensor(14)

In [54]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 997 µs


tensor(14)

In [55]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [56]:
# We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

In [57]:
# One of the ways to do this is with a transpose (switch the dimensions of a given tensor).
# You can perform transposes in PyTorch using either:
#     torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
#     tensor.T - where tensor is the desired tensor to transpose.

In [58]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B, "\n")

# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]]) 

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [59]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} (inner dimensions match)\n")
print("Output:")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"Output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) (inner dimensions match)

Output:
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
Output shape: torch.Size([3, 3])


In [60]:
# You can also use torch.mm() which is a short for torch.matmul().

# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [61]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}")
print(f"Output:\n{output}\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])
Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)
Output shape: torch.Size([3, 6])


In [62]:
# Finding the min, max, mean, sum, etc. (aggregation: go from more values to fewer values)

In [63]:
# First we'll create a tensor and then find the max, min, mean and sum of it.

# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [65]:
# You can also do the same as above with torch methods.
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(0), tensor(90), tensor(45.), tensor(450))

In [66]:
# Positional min/max

# You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

In [67]:
# Create a tensor
tensor = torch.arange(0, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 9
Index where min value occurs: 0


In [68]:
# Change tensor datatype
# You can change the datatypes of tensors using torch.Tensor.type(dtype=None) where the dtype parameter is the datatype you'd like to use.

In [69]:
# Create a tensor and check its datatype
tensor = torch.arange(0., 100., 10.)
tensor.dtype

torch.float32

In [70]:
# Now we'll create another tensor the same as before but change its datatype to torch.float16.

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [71]:
# And we can do something similar to make a torch.int8 tensor.

# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [72]:
# Reshaping, stacking, squeezing and unsqueezing
#     torch.reshape(input, shape): Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
#     Tensor.view(shape): Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
#     torch.stack(tensors, dim=0): Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
#     torch.squeeze(input): Squeezes input to remove all the dimenions with value 1.
#     torch.unsqueeze(input, dim): Returns input with a dimension value of 1 added at dim.
#     torch.permute(input, dims): Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [73]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.ndim, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), 1, torch.Size([7]), torch.float32)

In [74]:
# Add an extra dimension with torch.reshape().
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.ndim, x_reshaped.shape, x_reshaped.dtype

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), 2, torch.Size([1, 7]), torch.float32)

In [75]:
# Change the view with torch.view(). (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.ndim, z.shape, z.dtype

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), 2, torch.Size([1, 7]), torch.float32)

In [76]:
# Changing the view changes the original tensor too.
z[:, 0] = 66
z, x

(tensor([[66.,  2.,  3.,  4.,  5.,  6.,  7.]]),
 tensor([66.,  2.,  3.,  4.,  5.,  6.,  7.]))

In [77]:
# If we wanted to stack our new tensor on top of itself five times, we could do so with torch.stack().

# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
print(x_stacked)
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
print(x_stacked)

tensor([[66.,  2.,  3.,  4.,  5.,  6.,  7.],
        [66.,  2.,  3.,  4.,  5.,  6.,  7.],
        [66.,  2.,  3.,  4.,  5.,  6.,  7.],
        [66.,  2.,  3.,  4.,  5.,  6.,  7.]])
tensor([[66., 66., 66., 66.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.]])


In [78]:
# Removing all single dimensions from a tensor by using torch.squeeze().

In [79]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[66.,  2.,  3.,  4.,  5.,  6.,  7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([66.,  2.,  3.,  4.,  5.,  6.,  7.])
New shape: torch.Size([7])


In [80]:
# To do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.

In [81]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([66.,  2.,  3.,  4.,  5.,  6.,  7.])
Previous shape: torch.Size([7])

New tensor: tensor([[66.,  2.,  3.,  4.,  5.,  6.,  7.]])
New shape: torch.Size([1, 7])


In [82]:
# You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

In [83]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [84]:
# Indexing (selecting data from tensors)

# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.ndim, x.shape, x.dtype

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([1, 3, 3]),
 torch.int64)

In [85]:
# Indexing values goes outer dimension -> inner dimension (check out the square brackets).

# Let's index bracket by bracket
print(f"First square bracket: \n{x[0]}\n") 
print(f"Second square bracket: \n{x[0][0]}\n") 
print(f"Third square bracket: \n{x[0][0][0]}\n")

First square bracket: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Second square bracket: 
tensor([1, 2, 3])

Third square bracket: 
1



In [86]:
# You can also use : to specify "all values in this dimension" and then use a comma (,) to add another dimension.

# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [87]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [88]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [89]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [90]:
# PyTorch tensors & NumPy

In [91]:
# The two main methods you'll want to use for NumPy to PyTorch (and back again) are:
    # torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
    # torch.Tensor.numpy() - PyTorch tensor -> NumPy array.
    
import torch
import numpy as np

In [92]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, array.dtype, tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 torch.float64)

In [93]:
# By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).
# However, many PyTorch calculations default to using float32.
# So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).
tensor = torch.from_numpy(array).type(torch.float32)
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [94]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [95]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, tensor.dtype, numpy_tensor, numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

In [96]:
# Reproducibility (trying to take the random out of random)
# simulated randomness = simulated randomness

# start with random numbers -> tensor operations -> try to make better (again and again and again)
import torch

In [97]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [98]:
# What if you wanted to create two random tensors with the same values.

# That's where torch.manual_seed(seed) comes in, where seed is an integer (like 42, but it could be anything) that flavours the randomness.

In [99]:
import torch
import random

# Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [100]:
# Running tensors on GPUs (and making faster computations)

In [101]:
!nvidia-smi

Tue Jan 16 16:01:41 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.99                 Driver Version: 536.99       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce 940MX         WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P8              N/A / 200W |      0MiB /  2048MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [102]:
# You can test if PyTorch has access to a GPU using torch.cuda.is_available().

# Check for GPU
import torch
torch.cuda.is_available()

True

In [103]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [104]:
# Count number of devices
torch.cuda.device_count()

1

In [105]:
# Putting tensors (and models) on the GPU

# You can put tensors and models on a specific device by calling to(device) on them. Where device is the target device you'd like the tensor (or model) to go to.

# Putting a tensor on GPU using to(device) (e.g. some_tensor.to(device)) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. To overwrite tensors, reassign them:
#     some_tensor = some_tensor.to(device)

In [106]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor on CPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [107]:
# Moving tensors back to the CPU

# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy() # can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [108]:
# To get a tensor back to CPU and usable with NumPy we can use Tensor.cpu().

# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [109]:
# The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU.
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')